package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2015) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.builtins.AggregateMedia;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.builtins.RichArtifact;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_collection;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scope;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class AggregateSelfmadeDeclaration extends RichArtifact<AggregateMedia>
{
	@simpl_collection
	@simpl_scope("rich_artifacts_scope")
	@mm_name("rich_artifacts")
	private List<RichArtifact> richArtifacts;

	public AggregateSelfmadeDeclaration()
	{ super(); }

	public AggregateSelfmadeDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public List<RichArtifact> getRichArtifacts()
	{
		return richArtifacts;
	}

  // lazy evaluation:
  public List<RichArtifact> richArtifacts()
  {
    if (richArtifacts == null)
      richArtifacts = new ArrayList<RichArtifact>();
    return richArtifacts;
  }

  // addTo:
  public void addToRichArtifacts(RichArtifact element)
  {
    richArtifacts().add(element);
  }

  // size:
  public int richArtifactsSize()
  {
    return richArtifacts == null ? 0 : richArtifacts.size();
  }

	public void setRichArtifacts(List<RichArtifact> richArtifacts)
	{
		this.richArtifacts = richArtifacts;
	}
}
