package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2014) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.Metadata;
import ecologylab.bigsemantics.metadata.builtins.Document;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.builtins.RichArtifact;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metadata.scalar.MetadataString;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_composite;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import ecologylab.serialization.annotations.simpl_scope;
import ecologylab.serialization.annotations.simpl_wrap;
import java.lang.String;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class ClippingDeclaration<M extends Metadata> extends RichArtifact<M>
{
	@simpl_composite
	@simpl_wrap
	@simpl_scope("repository_documents")
	@mm_name("source_doc")
	private Document sourceDoc;

	@simpl_scalar
	private MetadataString xpath;

	@simpl_scalar
	private MetadataString caption;

	public ClippingDeclaration()
	{ super(); }

	public ClippingDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public Document getSourceDoc()
	{
		return sourceDoc;
	}

	public void setSourceDoc(Document sourceDoc)
	{
		this.sourceDoc = sourceDoc;
	}

	public MetadataString	xpath()
	{
		MetadataString	result = this.xpath;
		if (result == null)
		{
			result = new MetadataString();
			this.xpath = result;
		}
		return result;
	}

	public String getXpath()
	{
		return this.xpath == null ? null : xpath().getValue();
	}

	public MetadataString getXpathMetadata()
	{
		return xpath;
	}

	public void setXpath(String xpath)
	{
		if (xpath != null)
			this.xpath().setValue(xpath);
	}

	public void setXpathMetadata(MetadataString xpath)
	{
		this.xpath = xpath;
	}

	public MetadataString	caption()
	{
		MetadataString	result = this.caption;
		if (result == null)
		{
			result = new MetadataString();
			this.caption = result;
		}
		return result;
	}

	public String getCaption()
	{
		return this.caption == null ? null : caption().getValue();
	}

	public MetadataString getCaptionMetadata()
	{
		return caption;
	}

	public void setCaption(String caption)
	{
		if (caption != null)
			this.caption().setValue(caption);
	}

	public void setCaptionMetadata(MetadataString caption)
	{
		this.caption = caption;
	}
}
