package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2016) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.Metadata;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.builtins.person.author.IdeaMacheUser;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metadata.scalar.MetadataDate;
import ecologylab.bigsemantics.metadata.scalar.MetadataInteger;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_composite;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.Integer;
import java.util.Date;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class CreativeActDeclaration extends Metadata
{
	@simpl_scalar
	private MetadataInteger action;

	@simpl_composite
	@mm_name("creator")
	private IdeaMacheUser creator;

	@simpl_scalar
	private MetadataDate time;

	public CreativeActDeclaration()
	{ super(); }

	public CreativeActDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataInteger	action()
	{
		MetadataInteger	result = this.action;
		if (result == null)
		{
			result = new MetadataInteger();
			this.action = result;
		}
		return result;
	}

	public Integer getAction()
	{
		return this.action == null ? 0 : action().getValue();
	}

	public MetadataInteger getActionMetadata()
	{
		return action;
	}

	public void setAction(Integer action)
	{
		if (action != 0)
			this.action().setValue(action);
	}

	public void setActionMetadata(MetadataInteger action)
	{
		this.action = action;
	}

	public IdeaMacheUser getCreator()
	{
		return creator;
	}

	public void setCreator(IdeaMacheUser creator)
	{
		this.creator = creator;
	}

	public MetadataDate	time()
	{
		MetadataDate	result = this.time;
		if (result == null)
		{
			result = new MetadataDate();
			this.time = result;
		}
		return result;
	}

	public Date getTime()
	{
		return this.time == null ? null : time().getValue();
	}

	public MetadataDate getTimeMetadata()
	{
		return time;
	}

	public void setTime(Date time)
	{
		if (time != null)
			this.time().setValue(time);
	}

	public void setTimeMetadata(MetadataDate time)
	{
		this.time = time;
	}
}
