package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2015) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.builtins.PresentationFrame;
import ecologylab.bigsemantics.metadata.builtins.RichArtifact;
import ecologylab.bigsemantics.metadata.scalar.MetadataFloat;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.Float;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class FrameSelfmadeDeclaration extends RichArtifact<PresentationFrame>
{
	@simpl_scalar
	private MetadataFloat frameNumber;

	public FrameSelfmadeDeclaration()
	{ super(); }

	public FrameSelfmadeDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataFloat	frameNumber()
	{
		MetadataFloat	result = this.frameNumber;
		if (result == null)
		{
			result = new MetadataFloat();
			this.frameNumber = result;
		}
		return result;
	}

	public Float getFrameNumber()
	{
		return this.frameNumber == null ? 0 : frameNumber().getValue();
	}

	public MetadataFloat getFrameNumberMetadata()
	{
		return frameNumber;
	}

	public void setFrameNumber(Float frameNumber)
	{
		if (frameNumber != 0)
			this.frameNumber().setValue(frameNumber);
	}

	public void setFrameNumberMetadata(MetadataFloat frameNumber)
	{
		this.frameNumber = frameNumber;
	}
}
