package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2016) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.Metadata;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.scalar.MetadataString;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.String;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class HtmlTextDeclaration extends Metadata
{
	@simpl_scalar
	private MetadataString text;

	@simpl_scalar
	private MetadataString htmlString;

	public HtmlTextDeclaration()
	{ super(); }

	public HtmlTextDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataString	text()
	{
		MetadataString	result = this.text;
		if (result == null)
		{
			result = new MetadataString();
			this.text = result;
		}
		return result;
	}

	public String getText()
	{
		return this.text == null ? null : text().getValue();
	}

	public MetadataString getTextMetadata()
	{
		return text;
	}

	public void setText(String text)
	{
		if (text != null)
			this.text().setValue(text);
	}

	public void setTextMetadata(MetadataString text)
	{
		this.text = text;
	}

	public MetadataString	htmlString()
	{
		MetadataString	result = this.htmlString;
		if (result == null)
		{
			result = new MetadataString();
			this.htmlString = result;
		}
		return result;
	}

	public String getHtmlString()
	{
		return this.htmlString == null ? null : htmlString().getValue();
	}

	public MetadataString getHtmlStringMetadata()
	{
		return htmlString;
	}

	public void setHtmlString(String htmlString)
	{
		if (htmlString != null)
			this.htmlString().setValue(htmlString);
	}

	public void setHtmlStringMetadata(MetadataString htmlString)
	{
		this.htmlString = htmlString;
	}
}
