package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2015) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.SimplTypesScope;
import java.util.List;
import java.util.Map;

public class MetadataBuiltinDeclarationsTranslationScope
{

	protected static final Class TRANSLATIONS[] =
	{
		ecologylab.bigsemantics.metadata.Metadata.class,

		ecologylab.bigsemantics.metadata.builtins.Annotate.class,

		ecologylab.bigsemantics.metadata.builtins.AssignPrimaryLink.class,

		ecologylab.bigsemantics.metadata.builtins.Audio.class,

		ecologylab.bigsemantics.metadata.builtins.ClippableDocument.class,

		ecologylab.bigsemantics.metadata.builtins.Clipping.class,

		ecologylab.bigsemantics.metadata.builtins.ContactPoint.class,

		ecologylab.bigsemantics.metadata.builtins.CreativeAct.class,

		ecologylab.bigsemantics.metadata.builtins.CurateLink.class,

		ecologylab.bigsemantics.metadata.builtins.DebugMetadata.class,

		ecologylab.bigsemantics.metadata.builtins.Document.class,

		ecologylab.bigsemantics.metadata.builtins.DocumentMetadataWrap.class,

		ecologylab.bigsemantics.metadata.builtins.GisLocation.class,

		ecologylab.bigsemantics.metadata.builtins.HtmlText.class,

		ecologylab.bigsemantics.metadata.builtins.Image.class,

		ecologylab.bigsemantics.metadata.builtins.ImageClipping.class,

		ecologylab.bigsemantics.metadata.builtins.ImageSelfmade.class,

		ecologylab.bigsemantics.metadata.builtins.PersistenceMetaInfo.class,

		ecologylab.bigsemantics.metadata.builtins.RichArtifact.class,

		ecologylab.bigsemantics.metadata.builtins.RichDocument.class,

		ecologylab.bigsemantics.metadata.builtins.SequencedClippableDocument.class,

		ecologylab.bigsemantics.metadata.builtins.TextClipping.class,

		ecologylab.bigsemantics.metadata.builtins.TextSelfmade.class,

		ecologylab.bigsemantics.metadata.builtins.Video.class,

		ecologylab.bigsemantics.metadata.builtins.comment.Comment.class,

		ecologylab.bigsemantics.metadata.builtins.comment.Rating.class,

		ecologylab.bigsemantics.metadata.builtins.creativeWork.CreativeWork.class,

		ecologylab.bigsemantics.metadata.builtins.creativeWork.Curation.class,

		ecologylab.bigsemantics.metadata.builtins.person.BirthDetail.class,

		ecologylab.bigsemantics.metadata.builtins.person.Person.class,

		ecologylab.bigsemantics.metadata.builtins.person.author.Author.class,

		ecologylab.bigsemantics.metadata.builtins.person.author.IdeaMacheUser.class,

	};

	public static SimplTypesScope get()
	{
		return SimplTypesScope.get("repository_builtin_declarations_scope", TRANSLATIONS);
	}

}
