package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2014) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.Metadata;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metadata.scalar.MetadataDate;
import ecologylab.bigsemantics.metadata.scalar.MetadataParsedURL;
import ecologylab.bigsemantics.metadata.scalar.MetadataString;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.net.ParsedURL;
import ecologylab.serialization.annotations.simpl_collection;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.String;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

/** 
 *The PersistenceMetaInfo Class
 */ 
@simpl_inherit
public class PersistenceMetaInfoDeclaration extends Metadata
{
	@simpl_scalar
	private MetadataString docId;

	@simpl_scalar
	private MetadataParsedURL location;

	@simpl_collection("additional_location")
	@mm_name("additional_locations")
	private List<MetadataParsedURL> additionalLocations;

	@simpl_scalar
	private MetadataString charset;

	@simpl_scalar
	private MetadataString mimeType;

	@simpl_scalar
	private MetadataDate accessTime;

	@simpl_scalar
	private MetadataDate persistenceTime;

	@simpl_scalar
	private MetadataString mmdHash;

	public PersistenceMetaInfoDeclaration()
	{ super(); }

	public PersistenceMetaInfoDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataString	docId()
	{
		MetadataString	result = this.docId;
		if (result == null)
		{
			result = new MetadataString();
			this.docId = result;
		}
		return result;
	}

	public String getDocId()
	{
		return this.docId == null ? null : docId().getValue();
	}

	public MetadataString getDocIdMetadata()
	{
		return docId;
	}

	public void setDocId(String docId)
	{
		if (docId != null)
			this.docId().setValue(docId);
	}

	public void setDocIdMetadata(MetadataString docId)
	{
		this.docId = docId;
	}

	public MetadataParsedURL	location()
	{
		MetadataParsedURL	result = this.location;
		if (result == null)
		{
			result = new MetadataParsedURL();
			this.location = result;
		}
		return result;
	}

	public ParsedURL getLocation()
	{
		return this.location == null ? null : location().getValue();
	}

	public MetadataParsedURL getLocationMetadata()
	{
		return location;
	}

	public void setLocation(ParsedURL location)
	{
		if (location != null)
			this.location().setValue(location);
	}

	public void setLocationMetadata(MetadataParsedURL location)
	{
		this.location = location;
	}

	public List<MetadataParsedURL> getAdditionalLocations()
	{
		return additionalLocations;
	}

  // lazy evaluation:
  public List<MetadataParsedURL> additionalLocations()
  {
    if (additionalLocations == null)
      additionalLocations = new ArrayList<MetadataParsedURL>();
    return additionalLocations;
  }

  // addTo:
  public void addToAdditionalLocations(MetadataParsedURL element)
  {
    additionalLocations().add(element);
  }

  // size:
  public int additionalLocationsSize()
  {
    return additionalLocations == null ? 0 : additionalLocations.size();
  }

	public void setAdditionalLocations(List<MetadataParsedURL> additionalLocations)
	{
		this.additionalLocations = additionalLocations;
	}

	public MetadataString	charset()
	{
		MetadataString	result = this.charset;
		if (result == null)
		{
			result = new MetadataString();
			this.charset = result;
		}
		return result;
	}

	public String getCharset()
	{
		return this.charset == null ? null : charset().getValue();
	}

	public MetadataString getCharsetMetadata()
	{
		return charset;
	}

	public void setCharset(String charset)
	{
		if (charset != null)
			this.charset().setValue(charset);
	}

	public void setCharsetMetadata(MetadataString charset)
	{
		this.charset = charset;
	}

	public MetadataString	mimeType()
	{
		MetadataString	result = this.mimeType;
		if (result == null)
		{
			result = new MetadataString();
			this.mimeType = result;
		}
		return result;
	}

	public String getMimeType()
	{
		return this.mimeType == null ? null : mimeType().getValue();
	}

	public MetadataString getMimeTypeMetadata()
	{
		return mimeType;
	}

	public void setMimeType(String mimeType)
	{
		if (mimeType != null)
			this.mimeType().setValue(mimeType);
	}

	public void setMimeTypeMetadata(MetadataString mimeType)
	{
		this.mimeType = mimeType;
	}

	public MetadataDate	accessTime()
	{
		MetadataDate	result = this.accessTime;
		if (result == null)
		{
			result = new MetadataDate();
			this.accessTime = result;
		}
		return result;
	}

	public Date getAccessTime()
	{
		return this.accessTime == null ? null : accessTime().getValue();
	}

	public MetadataDate getAccessTimeMetadata()
	{
		return accessTime;
	}

	public void setAccessTime(Date accessTime)
	{
		if (accessTime != null)
			this.accessTime().setValue(accessTime);
	}

	public void setAccessTimeMetadata(MetadataDate accessTime)
	{
		this.accessTime = accessTime;
	}

	public MetadataDate	persistenceTime()
	{
		MetadataDate	result = this.persistenceTime;
		if (result == null)
		{
			result = new MetadataDate();
			this.persistenceTime = result;
		}
		return result;
	}

	public Date getPersistenceTime()
	{
		return this.persistenceTime == null ? null : persistenceTime().getValue();
	}

	public MetadataDate getPersistenceTimeMetadata()
	{
		return persistenceTime;
	}

	public void setPersistenceTime(Date persistenceTime)
	{
		if (persistenceTime != null)
			this.persistenceTime().setValue(persistenceTime);
	}

	public void setPersistenceTimeMetadata(MetadataDate persistenceTime)
	{
		this.persistenceTime = persistenceTime;
	}

	public MetadataString	mmdHash()
	{
		MetadataString	result = this.mmdHash;
		if (result == null)
		{
			result = new MetadataString();
			this.mmdHash = result;
		}
		return result;
	}

	public String getMmdHash()
	{
		return this.mmdHash == null ? null : mmdHash().getValue();
	}

	public MetadataString getMmdHashMetadata()
	{
		return mmdHash;
	}

	public void setMmdHash(String mmdHash)
	{
		if (mmdHash != null)
			this.mmdHash().setValue(mmdHash);
	}

	public void setMmdHashMetadata(MetadataString mmdHash)
	{
		this.mmdHash = mmdHash;
	}
}
