package ecologylab.bigsemantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2014) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.Metadata;
import ecologylab.bigsemantics.metadata.builtins.CreativeAct;
import ecologylab.bigsemantics.metadata.builtins.Document;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_collection;
import ecologylab.serialization.annotations.simpl_composite;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scope;
import ecologylab.serialization.annotations.simpl_wrap;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class RichArtifactDeclaration<M extends Metadata> extends Metadata
{
	@simpl_composite
	@simpl_wrap
	@simpl_scope("repository_media")
	@mm_name("media")
	private M media;

	@simpl_collection
	@simpl_scope("creative_acts_scope")
	@mm_name("creative_acts")
	private List<CreativeAct> creativeActs;

	@simpl_collection("document")
	@mm_name("outlinks")
	private List<Document> outlinks;

	public RichArtifactDeclaration()
	{ super(); }

	public RichArtifactDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public M getMedia()
	{
		return media;
	}

	public void setMedia(M media)
	{
		this.media = media;
	}

	public List<CreativeAct> getCreativeActs()
	{
		return creativeActs;
	}

  // lazy evaluation:
  public List<CreativeAct> creativeActs()
  {
    if (creativeActs == null)
      creativeActs = new ArrayList<CreativeAct>();
    return creativeActs;
  }

  // addTo:
  public void addToCreativeActs(CreativeAct element)
  {
    creativeActs().add(element);
  }

  // size:
  public int creativeActsSize()
  {
    return creativeActs == null ? 0 : creativeActs.size();
  }

	public void setCreativeActs(List<CreativeAct> creativeActs)
	{
		this.creativeActs = creativeActs;
	}

	public List<Document> getOutlinks()
	{
		return outlinks;
	}

  // lazy evaluation:
  public List<Document> outlinks()
  {
    if (outlinks == null)
      outlinks = new ArrayList<Document>();
    return outlinks;
  }

  // addTo:
  public void addToOutlinks(Document element)
  {
    outlinks().add(element);
  }

  // size:
  public int outlinksSize()
  {
    return outlinks == null ? 0 : outlinks.size();
  }

	public void setOutlinks(List<Document> outlinks)
	{
		this.outlinks = outlinks;
	}
}
