package ecologylab.semantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2012) Interface Ecology Lab.
 */

import ecologylab.semantics.metadata.builtins.Image;
import ecologylab.semantics.metadata.builtins.MediaClipping;
import ecologylab.semantics.metametadata.MetaMetadataCompositeField;
import ecologylab.serialization.annotations.simpl_inherit;

@simpl_inherit
public class ImageClippingDeclaration extends MediaClipping<Image>
{
	public ImageClippingDeclaration()
	{ super(); }

	public ImageClippingDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}

}
