package ecologylab.semantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2012) Interface Ecology Lab.
 */

import ecologylab.semantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.semantics.metametadata.MetaMetadataCompositeField;
import ecologylab.semantics.namesandnums.SemanticsNames;
import ecologylab.serialization.SimplTypesScope;
import java.util.List;
import java.util.Map;

public class MetadataBuiltinDeclarationsTranslationScope
{

	protected static final Class TRANSLATIONS[] =
	{
		ecologylab.semantics.metadata.builtins.declarations.AnnotationDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.ClippableDocumentDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.ClippingDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.CompoundDocumentDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.DebugMetadataDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.DocumentDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.DocumentMetadataWrapDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.ImageClippingDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.ImageDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.InformationCompositionDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.MediaClippingDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.MetadataDeclaration.class,

		ecologylab.semantics.metadata.builtins.declarations.TextClippingDeclaration.class,

	};

	public static SimplTypesScope get()
	{
		return SimplTypesScope.get("repository_builtin_declarations_scope", TRANSLATIONS);
	}

}
