package ecologylab.semantics.metadata.builtins.declarations;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2013) Interface Ecology Lab.
 */

import ecologylab.semantics.metadata.Metadata;
import ecologylab.semantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.semantics.metadata.scalar.MetadataDate;
import ecologylab.semantics.metadata.scalar.MetadataString;
import ecologylab.semantics.metametadata.MetaMetadataCompositeField;
import ecologylab.semantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.String;
import java.util.Date;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class AnnotationDeclaration extends Metadata
{
	@simpl_scalar
	private MetadataString text;

	@simpl_scalar
	private MetadataString author;

	@simpl_scalar
	private MetadataDate creationTime;

	public AnnotationDeclaration()
	{ super(); }

	public AnnotationDeclaration(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataString	text()
	{
		MetadataString	result = this.text;
		if (result == null)
		{
			result = new MetadataString();
			this.text = result;
		}
		return result;
	}

	public String getText()
	{
		return this.text == null ? null : text().getValue();
	}

	public MetadataString getTextMetadata()
	{
		return text;
	}

	public void setText(String text)
	{
		if (text != null)
			this.text().setValue(text);
	}

	public void setTextMetadata(MetadataString text)
	{
		this.text = text;
	}

	public MetadataString	author()
	{
		MetadataString	result = this.author;
		if (result == null)
		{
			result = new MetadataString();
			this.author = result;
		}
		return result;
	}

	public String getAuthor()
	{
		return this.author == null ? null : author().getValue();
	}

	public MetadataString getAuthorMetadata()
	{
		return author;
	}

	public void setAuthor(String author)
	{
		if (author != null)
			this.author().setValue(author);
	}

	public void setAuthorMetadata(MetadataString author)
	{
		this.author = author;
	}

	public MetadataDate	creationTime()
	{
		MetadataDate	result = this.creationTime;
		if (result == null)
		{
			result = new MetadataDate();
			this.creationTime = result;
		}
		return result;
	}

	public Date getCreationTime()
	{
		return this.creationTime == null ? null : creationTime().getValue();
	}

	public MetadataDate getCreationTimeMetadata()
	{
		return creationTime;
	}

	public void setCreationTime(Date creationTime)
	{
		if (creationTime != null)
			this.creationTime().setValue(creationTime);
	}

	public void setCreationTimeMetadata(MetadataDate creationTime)
	{
		this.creationTime = creationTime;
	}
}
